python jsonParser.py ebay_data/items-0.json
python jsonParser.py ebay_data/items-1.json
python jsonParser.py ebay_data/items-2.json
python jsonParser.py ebay_data/items-3.json
python jsonParser.py ebay_data/items-4.json
python jsonParser.py ebay_data/items-5.json
python jsonParser.py ebay_data/items-6.json
python jsonParser.py ebay_data/items-7.json
python jsonParser.py ebay_data/items-8.json
python jsonParser.py ebay_data/items-9.json
python jsonParser.py ebay_data/items-10.json
python jsonParser.py ebay_data/items-11.json
python jsonParser.py ebay_data/items-12.json
python jsonParser.py ebay_data/items-13.json
python jsonParser.py ebay_data/items-14.json
python jsonParser.py ebay_data/items-15.json
python jsonParser.py ebay_data/items-16.json
python jsonParser.py ebay_data/items-17.json
python jsonParser.py ebay_data/items-18.json
python jsonParser.py ebay_data/items-19.json
python jsonParser.py ebay_data/items-20.json
python jsonParser.py ebay_data/items-21.json
python jsonParser.py ebay_data/items-22.json
python jsonParser.py ebay_data/items-23.json
python jsonParser.py ebay_data/items-24.json
python jsonParser.py ebay_data/items-25.json
python jsonParser.py ebay_data/items-26.json
python jsonParser.py ebay_data/items-27.json
python jsonParser.py ebay_data/items-28.json
python jsonParser.py ebay_data/items-29.json
python jsonParser.py ebay_data/items-30.json
python jsonParser.py ebay_data/items-31.json
python jsonParser.py ebay_data/items-32.json
python jsonParser.py ebay_data/items-33.json
python jsonParser.py ebay_data/items-34.json
python jsonParser.py ebay_data/items-35.json
python jsonParser.py ebay_data/items-36.json
python jsonParser.py ebay_data/items-37.json
python jsonParser.py ebay_data/items-38.json
python jsonParser.py ebay_data/items-39.json
echo 'DONE'